---
- hosts: consulhosts
  become: True
  vars:
    dnsmasq_consul_postfix: consul
    dnsmasq_consul_host: 127.0.0.1
    dnsmasq_consul_port: 8600
    dnsmasq_consul_rev_servers: []
  tasks:
  - name: "ensure dnsmasq is installed"
    package:
      name: "dnsmasq"
      state: present
  - name: "copy config for consul dns resolution"
    template:
      src: "10-consul.j2"
      dest: "/etc/dnsmasq.d/10-consul"
    notify: restart dnsmasq
  handlers:
  - name: "restart dnsmasq"
    service:
      name: dnsmasq
      state: restarted
      enabled: True
