- hosts: prometheus-servers
  become: True
  tasks:
  - name: "create config dir"
    file:
      path: "/etc/prometheus"
      state: directory
      mode: "0755"
  - name: "create prometheus config"
    template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
  - name: "start container"
    docker_container:
      name: prometheus
      image: "prom/prometheus"
      ports:
      - "9090:9090"
      volumes:
      - "/etc/prometheus:/etc/prometheus"
      - "/etc/consul/ssl/ca.pem:/etc/consul/ssl/ca.pem"
      restart_policy: unless-stopped
      restart: True
  - name: register prometheus service
    consul: 
      service_name: prometheus
      service_port: "9090"
      service_address: "{{ansible_host}}"
      interval: 2m
      http: http://{{ansible_host}}:9090